### ISSUE TITLE
Inconsistency in Release Tags

### ISSUE THREAD

**Issue by keenranger** [dreipol/pyattest#11]
Hi,

I noticed an inconsistency in the release tags. The previous tags follow the pattern 0.0.x, but the new tag is 0.1.13. Additionally, the PyPI version history also follows the 0.0.x pattern.

GitHub Releases: [Link](https://github.com/dreipol/pyattest/releases/tag/v0.1.13)
PyPI Version History: [Link](https://pypi.org/project/pyattest/#history)

Could you please check and correct this discrepancy?

Thanks!

**Comment by lailabecker** [comment]
Thanks for the heads-up. 0.0.13 is correct. I've fixed it now.
