### ISSUE TITLE
GooglePlayIntegrityAttestationVerifier does not set verified_data

### ISSUE THREAD

**Issue by o15a3d4l11s2** [dreipol/pyattest#12]
The class `GooglePlayIntegrityAttestationVerifier` does not set any verified data by `def verified_data(self, data: dict)`. As a comparison `GoogleAttestationVerifier` and `AppleAttestationVerifier` call it.

This means that after `verify()`, the flag `verified` stays `False`.
I think it should either set `verified_data` or at least set `verified = True` at the end of the `verify()` process.

**Comment by lailabecker** [comment]
Thanks for the heads up! It should be fixed in v1.0.0 now

**Comment by o15a3d4l11s2** [comment]
Thank you for the fast reaction. I was going to do a PR, but by that time I saw you already resolved it.
